
Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./test/attacker_test.sol


[0m[0m
[0m  attacker_test[0m
  [32m  âœ“[0m[90m testBankDeployment[0m[33m (59ms)[0m
  [32m  âœ“[0m[90m testAttackerDeployment[0m[33m (63ms)[0m
  [32m  âœ“[0m[90m testAttack[0m[31m (155ms)[0m
  [32m  âœ“[0m[90m testBankMoneyDrained[0m[33m (41ms)[0m
  [32m  âœ“[0m[90m testAttackerMoneyReceived[0m[33m (38ms)[0m


[92m [0m[32m 5 passing[0m[90m (7s)[0m
Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./test/bank_test.sol


[0m[0m
[0m  bank_test[0m
  [32m  âœ“[0m[90m testSetup[0m[33m (69ms)[0m
  [31m  1) testAttackBank[0m
    > No events were emitted
  [32m  âœ“[0m[90m testSafeAgainstReentrancy[0m[33m (51ms)[0m


[92m [0m[32m 2 passing[0m[90m (7s)[0m
[31m  1 failing[0m

[0m  1) bank_test
       testAttackBank:
[0m[31m     Error: Returned error: VM Exception while processing transaction: revert[0m[90m
     at PromiEvent (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:6:1)
      at TruffleContract.testAttackBank (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:157:1)
      at abstraction.deployed.then.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/soliditytest.js:97:1)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
[0m
